version: '3.8'
services:
  vite:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:latest
    ports:
      - "5225:5225"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vite